# Generated by Django 4.1 on 2022-08-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='course_image'),
        ),
    ]
