# Generated by Django 4.1 on 2022-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='cancel_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
