# Generated by Django 4.1 on 2022-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrol',
            field=models.IntegerField(default=0),
        ),
    ]
