# Generated by Django 4.1 on 2022-09-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_lesson_options_alter_chapter_course_and_more'),
        ('enrollment', '0002_remove_enrollment_course_enrollment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reason_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='withdrawal',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='curriculum.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='enrollment.enrollment'),
        ),
    ]
